routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\SubcategoryController;
use App\Http\Controllers\FrontProductController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::resource('category','CategoryController');

// Route::get('/category', [ CategoryController::class, 'category'] );


Route::get('subcatories/{id}', [ProductController::class, 'loadSubcategories'] );



// Route::get('/index/test', function () {
//     return view('layouts/test');
// });

Route::get('/', [FrontProductController::class, 'index']);

Route::get('product/{id}', [FrontProductController::class, 'show'] )->name('product.view');

Route::get('/category/{name}',[FrontProductController::class, 'allProduct'])->name('product.list');

Auth::routes();

// // buang nanti 
Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::get('/addToCart/{product}', [CartController::class, 'addToCart'])->name('add.cart');

Route::get('/cart', [CartController::class, 'showCart'])->name('cart.show');

Route::post('/products/{product}', [CartController::class, 'updateCart'])->name('cart.update');

Route::post('/product/{product}', [CartController::class, 'removeCart'])->name('cart.remove');

Route::get('/checkout/{amount}', [CartController::class, 'checkout'])->name('cart.checkout')->middleware('auth');

Route::post('/charge', [CartController::class, 'charge'])->name('cart.charge');

Route::get('/orders', [CartController::class, 'order'])->name('order')->middleware('auth');

Route::get('all/products', [FrontProductController::class, 'moreProducts'])->name('more.product');

// sementara
// Route::get('slider', [SliderController::class, 'index'])->name('slider.index');

// Route::get('slider/create', [SliderController::class, 'create'])->name('slider.create');

// Route::post('slider', [SliderController::class, 'store'])->name('slider.store');


Route::group(['prefix'=>'auth','middleware'=>['auth','isAdmin']], 
    function(){
    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('dashboard');
    
    Route::resource('category', CategoryController::class);

    Route::resource('subcategory', SubcategoryController::class);

    Route::resource('product', ProductController::class);

    Route::get('slider', [SliderController::class, 'index'])->name('slider.index');

    Route::get('slider/create', [SliderController::class, 'create'])->name('slider.create');

    Route::post('slider', [SliderController::class, 'store'])->name('slider.store');
    
    Route::post('slider/{id}', [SliderController::class, 'destroy'])->name('slider.destroy');

    Route::get('users', [UserController::class, 'index'])->name('user.index');

    Route::get('/orders', [CartController::class, 'userOrder'])->name('order.index');

    Route::get('/orders/{user_id}/{order_id}', [CartController::class, 'viewUserOrder'])->name('user.order');

    // Route::delete('slider/{id}','SliderController@destroy')->name('slider.destroy');
    // Route::delete('slider/{id}', [SliderController::class, 'destroy'])->name('slider.destroy');



});

app/Models/Subcategory.php
<?php

namespace App\Models;

use App\Models\Category;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Subcategory extends Model
{
    use HasFactory;
    protected $fillable = ['name','category_id'];

    public function category(){
        return $this->belongsTo(Category::class);
    }
}

app/Http/Controllers/SubcategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\Subcategory;
use Illuminate\Http\Request;

class SubcategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $subcategories = Subcategory::get();
        return view('admin.subcategory.index', compact('subcategories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = Category::get();
        return view('admin.subcategory.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'name'=>'required|min:3',
            'category'=>'required'
            ]);
        Subcategory::create([

                'name'=>$request->name,
                'category_id'=>$request->category

        ]);
            notify()->success('Subcategory created successfully!');
            return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $subcategory = Subcategory::find($id);
   
        return view('admin.subcategory.edit', compact('subcategory'));


    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $subcategory = Subcategory::find($id);
        $subcategory->name = $request->name;
        $subcategory->category_id = $request->category;
        $subcategory->save(); 
        notify()->success('Subcategory updated successfully!');
        return redirect()->route('subcategory.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $subcategory = Subcategory::find($id);
        $subcategory->delete();
        notify()->success('Subcategory deleted successfully!');
        return redirect()->route('subcategory.index');
    }
}

resources/views/admin/subcategory/create.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 ml-4 text-gray-800">SubCategory</h1>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="./">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">SubCategory</li>
            </ol>
    </div>

    <div class="row justify-content-center">
    

      <div class="col-lg-10">
        <form action="{{route('subcategory.store')}}" method="POST" >@csrf
              <div class="card mb-6">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Create SubCategory</h6>
                </div>
                <div class="card-body">
                    <div class="form-group"> 
                      <label for="">Name</label>
                      <input type="text" name="name" class="form-control @error('name') is-invalid @enderror " id="" aria-describedby=""
                        placeholder="Enter name of subcategory">
                        @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                      @enderror
                    
                    </div>
                    <div class="form-group">
                      <label for="">Choose Category</label>
                        <select name="category" class="form-control @error('category') is-invalid @enderror" >
                          <option value="">select</option>
                          @foreach($categories as $category)
                            <option value="{{$category->id}}">{{$category->name}}</option>
                          @endforeach

                        </select>

                       @error('category')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                      @enderror
                      
                    </div>
                 
                   
                    <button type="submit" class="btn btn-primary">Submit</button>
                 
                </div>
              </div>
            </form>

          </div>
</div>
@endsection

resources/views/admin/subcategory/edit.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 ml-4 text-gray-800">SubCategory</h1>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="./">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">SubCategory</li>
            </ol>
    </div>

    <div class="row justify-content-center">
    

      <div class="col-lg-10">
        <form action="{{route('subcategory.update',[$subcategory->id])}}" method="POST" >@csrf
          {{method_field('PUT')}}
              <div class="card mb-6">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Update SubCategory</h6>
                </div>
                <div class="card-body">
                    <div class="form-group"> 
                      <label for="">Name</label>
                      <input type="text" name="name" class="form-control @error('name') is-invalid @enderror " id="" aria-describedby=""
                        placeholder="Enter name of subcategory" value="{{$subcategory->name}}">
                        @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                      @enderror
                    
                    </div>
                    <div class="form-group">
                      <label for="">Choose Category</label>
                        <select name="category" class="form-control @error('category') is-invalid @enderror" >
                          <option value="">Select category</option>
                          @foreach(App\Models\Category::all() as $category)
                            <option value="{{$category->id}}"
                              @if($category->id == $subcategory->category_id) 
                              selected
                              @endif>
                              {{$category->name}}</option>
                          @endforeach

                        </select>

                       @error('category')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                      @enderror
                      
                    </div>
                 
                   
                    <button type="submit" class="btn btn-primary">Submit</button>
                 
                </div>
              </div>
            </form>

          </div>
</div>
@endsection

resources/views/admin/subcategory/index.blade.php
@extends('admin.layouts.main')

@section('content')

        <div class="container-fluid" id="container-wrapper">
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 text-gray-800">Category Tables</h1>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="./">Home</a></li>
              <li class="breadcrumb-item">Subategory</li>
              <li class="breadcrumb-item active" aria-current="page">Subcategory Tables</li>
            </ol>
          </div>

          <div class="row">
            <div class="col-lg-12 mb-4">
              <!-- Simple Tables -->
              <div class="card">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">All Subcategories</h6>
                </div>
                <div class="table-responsive">
                  <table class="table align-items-center table-flush">
                    <thead class="thead-light">
                      <tr>
                        <th>SN</th>
                        
                        <th>Name</th>
                        <th>Category</th>
                        <th>Action</th>
                        <th></th>
                      </tr>
                    </thead>
                    <tbody>
                      @if(count($subcategories)>0)
                      @foreach($subcategories as $key=>$subcategory)
                      <tr>

                        <td><a href="#">{{$key+1}}</a></td>
                        
                        <td>{{$subcategory->name}}</td>
                        <td>{{$subcategory->category->name}}</td>
                        
                        <td><a href="{{route('subcategory.edit',[$subcategory->id])}}" class="btn btn-sm btn-primary">Edit</a>

                         
                        </td>
                        <td>
                          <form action="{{route('subcategory.destroy',[$subcategory->id])}}" method="POST" onsubmit="return confirmDelete()">@csrf
                            {{method_field('DELETE')}}
                            <button type="submit" class="btn btn-sm btn-danger" >Delete</button>
                            
                          </form>
                        </td>
                      </tr>
                      @endforeach

                      @else
                      <td>No category created yet!</td>
                      @endif
                      
                      
                      
                    </tbody>
                  </table>
                </div>
                <div class="card-footer"></div>
              </div>
            </div>
          </div>
          <!--Row-->
        </div>

  @endsection