routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\CartController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\SubcategoryController;
use App\Http\Controllers\FrontProductController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

// Route::resource('category','CategoryController');

// Route::get('/category', [ CategoryController::class, 'category'] );


Route::get('subcatories/{id}', [ProductController::class, 'loadSubcategories'] );



// Route::get('/index/test', function () {
//     return view('layouts/test');
// });

Route::get('/', [FrontProductController::class, 'index']);

Route::get('product/{id}', [FrontProductController::class, 'show'] )->name('product.view');

Route::get('/category/{name}',[FrontProductController::class, 'allProduct'])->name('product.list');

Auth::routes();

// // buang nanti 
Route::get('/home', [HomeController::class, 'index'])->name('home');

Route::get('/addToCart/{product}', [CartController::class, 'addToCart'])->name('add.cart');

Route::get('/cart', [CartController::class, 'showCart'])->name('cart.show');

Route::post('/products/{product}', [CartController::class, 'updateCart'])->name('cart.update');

Route::post('/product/{product}', [CartController::class, 'removeCart'])->name('cart.remove');

Route::get('/checkout/{amount}', [CartController::class, 'checkout'])->name('cart.checkout')->middleware('auth');

Route::post('/charge', [CartController::class, 'charge'])->name('cart.charge');

Route::get('/orders', [CartController::class, 'order'])->name('order')->middleware('auth');

Route::get('all/products', [FrontProductController::class, 'moreProducts'])->name('more.product');

// sementara
// Route::get('slider', [SliderController::class, 'index'])->name('slider.index');

// Route::get('slider/create', [SliderController::class, 'create'])->name('slider.create');

// Route::post('slider', [SliderController::class, 'store'])->name('slider.store');


Route::group(['prefix'=>'auth','middleware'=>['auth','isAdmin']], 
    function(){
    Route::get('/dashboard', function () {
        return view('admin.dashboard');
    })->name('dashboard');
    
    Route::resource('category', CategoryController::class);

    Route::resource('subcategory', SubcategoryController::class);

    Route::resource('product', ProductController::class);

    Route::get('slider', [SliderController::class, 'index'])->name('slider.index');

    Route::get('slider/create', [SliderController::class, 'create'])->name('slider.create');

    Route::post('slider', [SliderController::class, 'store'])->name('slider.store');
    
    Route::post('slider/{id}', [SliderController::class, 'destroy'])->name('slider.destroy');

    Route::get('users', [UserController::class, 'index'])->name('user.index');

    Route::get('/orders', [CartController::class, 'userOrder'])->name('order.index');

    Route::get('/orders/{user_id}/{order_id}', [CartController::class, 'viewUserOrder'])->name('user.order');

    // Route::delete('slider/{id}','SliderController@destroy')->name('slider.destroy');
    // Route::delete('slider/{id}', [SliderController::class, 'destroy'])->name('slider.destroy');



});

app/Models/Product.php
<?php

namespace App\Models;

use App\Models\Category;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Product extends Model
{
    use HasFactory;

    protected $fillable = ['name','description','image','price', 'additional_info', 'category_id', 'subcategory_id'];

    public function category() {
        return $this->hasOne(Category::class, 'id', 'category_id');
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\Subcategory;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index(){
        $products = Product::get();
        return view('admin.product.index', compact('products'));
    }

    public function create(){
        return view('admin.product.create');
    }

    public function store(Request $request){

        $this->validate($request, [
            'name'=> 'required',
            'description'=> 'required|min:3',
            'image'=> 'required|mimes:jpeg,png',
            'price'=>'required|numeric',
            'additional_info' => 'required',
            'category'=>'required'
        ]);

        // store image into public/product file. 
        $image = $request->file('image')->store('public/product');

        // save data
        Product::create([
            'name' => $request->name,
            'description' => $request->description,
            'image' => $image,
            'price'=>  $request->price,
            'additional_info' => $request->additional_info,
            'category_id'=> $request->category,
            'subcategory_id' => $request->subcategory
        ]);

        notify()->success('Product created successfully!');
        return redirect()->back();
        // return view('admin.product.create');
    }

    public function loadSubcategories(Request $request, $id){
        $subcategory = Subcategory::where('category_id', $id)->pluck('name','id');
        return response()->json($subcategory);
    }

    public function edit($id){
        $product = Product::find($id);
        return view('admin.product.edit', compact('product'));
    }

    public function update(Request $request, $id){
        $product = Product::find($id);
        $image = $product->image;
        if($request->hasFile('image')){
            $image = $request->file('image')->store('public/product');
             \Storage::delete($product->image);
           
        
        $product->name = $request->name;
        $product->description= $request->description;
        $product->image=$image;
        $product->price= $request->price;
        $product->category_id= $request->category;
        $product->subcategory_id= $request->subcategory;
        $product->additional_info=$request->additional_info;
        $product->save();
        }else{
            $product->name = $request->name;
            $product->description= $request->description;
            $product->price= $request->price;
            $product->category_id= $request->category;
            $product->subcategory_id= $request->subcategory;
            $product->additional_info=$request->additional_info;
            $product->save();
        }

        notify()->success('Product updated successfully!');
        return redirect()->route('product.index');
    }

    public function destroy($id)
    {
        $product = Product::find($id);
        $filename = $product->image;
        $product->delete();
        \Storage::delete($filename);
        notify()->success('Product deleted successfully!');
        return redirect()->route('product.index');
    }

}

resources/views/admin/product/create.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 ml-4 text-gray-800">Product</h1>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="./">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Product</li>
            </ol>
    </div>

    <div class="row justify-content-center">
      @if(Session::has('message'))
        <div class="alert alert-success">
          {{Session::get('message')}}
        </div>

      @endif

      <div class="col-lg-10">
        <form action="{{route('product.store')}}" method="POST" enctype="multipart/form-data">@csrf
                <div class="card mb-6">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Create Category</h6>
                </div>
                <div class="card-body">
                    <div class="form-group"> 
                      <label for="">Name</label>
                      <input type="text" name="name" class="form-control @error('name') is-invalid @enderror " id="" aria-describedby=""
                        placeholder="Enter name of product">
                        @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                      @enderror
                    
                    </div>
                    <div class="form-group">
                      <label for="">Description</label>
                      <textarea name="description" id="summernote" class="form-control @error('description') is-invalid @enderror "></textarea>
                       @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                      @enderror
                      
                    </div>
                    <div class="form-group">
                      <div class="custom-file">
                        <input type="file" class="custom-file-input @error('image') is-invalid @enderror  " id="customFile" name="image">
                        <label class="custom-file-label  " for="customFile">Choose file</label>
                            @error('image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                          </span>
                      @enderror
                      </div>
                       
                    </div>

                      <div class="form-group"> 
                      <label for="">Price($)</label>
                      <input type="number" name="price" class="form-control @error('price') is-invalid @enderror " id="" aria-describedby=""
                        >
                        @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                      @enderror
                    
                    </div>
                      <div class="form-group">
                      <label for="">Additional information</label>
                      <textarea name="additional_info" id="summernote1" class="form-control @error('additional_info') is-invalid @enderror "></textarea>
                       @error('additional_info')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                      @enderror
                      
                    </div>
                <div class="form-group">
                      <label for="">Choose Category</label>
                        <select name="category"  class="form-control @error('category') is-invalid @enderror" >
                          <option value="">select</option>
                          @foreach(App\Models\Category::all() as $key=> $category)
                            <option value="{{$category->id}}">{{$category->name}}</option>
                          @endforeach

                        </select>

                       @error('category')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                      @enderror
                      
                    </div>

            
                <div class="form-group">
                      <label for="">Choose Subcategory</label>
                        <select name="subcategory"  class="form-control @error('subcategory') is-invalid @enderror" >

                          <option value="">select</option>
                          

                        </select>

                    
                      
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                 
                </div>
              </div>
            </form>

          </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript">
    $("document").ready(function(){
        $('select[name="category"]').on('change',function(){
            var catId = $(this).val();
            if(catId){
                $.ajax({

                    url:'/subcatories/'+catId,
                    type:"GET",
                    dataType:"json",
                    success:function(data){
                        $('select[name="subcategory"]').empty();
                        $.each(data,function(key,value){
                            $('select[name="subcategory"]').append('<option value=" '+key+'">'+value+'</option>');
                        })
                    }


                })
            }else{
              $('select[name="subcategory"]').empty();  
            }
        });


    });
</script>

@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 ml-4 text-gray-800">Product</h1>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="./">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Product</li>
            </ol>
    </div>

    <div class="row justify-content-center">
      @if(Session::has('message'))
        <div class="alert alert-success">
          {{Session::get('message')}}
        </div>

      @endif

      <div class="col-lg-10">
        <form action="{{route('product.update',[$product->id])}}" method="POST" enctype="multipart/form-data">@csrf
          {{method_field('PUT')}}
              <div class="card mb-6">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Update Product</h6>
                </div>
                <div class="card-body">
                    <div class="form-group"> 
                      <label for="">Name</label>
                      <input type="text" name="name" class="form-control @error('name') is-invalid @enderror " id="" aria-describedby=""
                        placeholder="Enter name of product" value="{{$product->name}}">
                        @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                      @enderror
                    
                    </div>
                    <div class="form-group">
                      <label for="">Description</label>
                      <textarea name="description" id="" class="form-control @error('description') is-invalid @enderror ">{!!$product->description!!}</textarea>
                       @error('description')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                      @enderror
                      
                    </div>
                    <div class="form-group">
                      <div class="custom-file">
                        <input type="file" class="custom-file-input @error('image') is-invalid @enderror  " id="customFile" name="image">
                        <label class="custom-file-label  " for="customFile">Choose file</label>
                       <center> <img src="{{Storage::url($product->image)}}" width="100"></center>
                            @error('image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                          </span>
                      @enderror
                      </div>
                       
                    </div>

                      <div class="form-group"> 
                      <label for="">Price($)</label>
                      <input type="text" name="price" class="form-control @error('price') is-invalid @enderror " id="" aria-describedby="" value="{{$product->price}}" 
                        >
                        @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                      @enderror
                    
                    </div>
                      <div class="form-group">
                      <label for="">Additinal information</label>
                      <textarea name="additional_info" id="summernote1" class="form-control @error('additional_info') is-invalid @enderror ">
                        {!!$product->additional_info!!}
                      </textarea>
                       @error('additional_info')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                      @enderror
                      
                    </div>
                    <div class="form-group">
                      <label for="">Choose Category</label>
                        <select name="category" class="form-control @error('category') is-invalid @enderror"  required="">
                          <option value="">select</option>
                          @foreach(App\Models\Category::all() as $category)
                            <option value="{{$category->id}}"
                              >{{$category->name}}</option>
                          @endforeach

                        </select>

                       @error('category')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                      @enderror
                      
                    </div>
                    <div class="form-group">
                      <label for="">Choose Subcategory</label>
                        <select name="subcategory"  class="form-control @error('subcategory') is-invalid @enderror" >

                          <option value="">select</option>
                          

                        </select>

                    
                      
                    </div>
                   
                    <button type="submit" class="btn btn-primary">Update</button>
                 
                </div>
              </div>
            </form>

          </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script type="text/javascript">
    $("document").ready(function(){
        $('select[name="category"]').on('change',function(){
            var catId = $(this).val();
            if(catId){
                $.ajax({

                    url:'/subcatories/'+catId,
                    type:"GET",
                    dataType:"json",
                    success:function(data){
                        $('select[name="subcategory"]').empty();
                        $.each(data,function(key,value){
                            $('select[name="subcategory"]').append('<option value=" '+key+'">'+value+'</option>');
                        })
                    }


                })
            }else{
              $('select[name="subcategory"]').empty();  
            }
        });


    });
</script>
@endsection

resources/views/admin/product/index.blade.php
@extends('admin.layouts.main')

@section('content')
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
            <h1 class="h3 mb-0 ml-4 text-gray-800">Product</h1>
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="./">Home</a></li>
              <li class="breadcrumb-item active" aria-current="page">Product</li>
            </ol>
    </div>
    <!-- Datatables -->
            <div class="col-lg-12">
              <div class="card mb-4">
                <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
                  <h6 class="m-0 font-weight-bold text-primary">Products</h6>
                </div>
                <div class="table-responsive p-3">
                  <table class="table align-items-center table-flush" id="dataTable">
                    <thead class="thead-light">
                      <tr>
                        <th>Image</th>
                        <th>Name</th>
                        <th>Description</th>
                        <th>Additional_info</th>
                        <th>Price</th>
                        <th>Category</th>
                        <th></th>
                        <th></th>
                        
                      </tr>
                    </thead>
                    
                    <tbody>
                      @if(count($products)>0)
                      @foreach($products as $product)
                      <tr>
                        <td>
                          <img src="{{Storage::url($product->image)}}" width="100">
                        </td>
                        <td>{{$product->name}}</td>
                        <td>{!!  $product->description !!}</td>
                        <td>{!!$product->additional_info!!}</td>
                        <td>${{$product->price}}</td>
                        <td>{{$product->category->name}}</td>
                        <td>
                          <a href="{{route('product.edit',[$product->id])}}">
                              <button class="btn btn-primary">Edit</button>
                          </a>
                        </td>
                        <td>
                           <form action="{{route('product.destroy',[$product->id])}}" method="POST" onsubmit="return confirmDelete()">@csrf
                            {{method_field('DELETE')}}
                            <button type="submit" class="btn btn-sm btn-danger" >Delete</button>
                            
                          </form>
                        </td>

                         
                      </tr>
                      @endforeach
                      @else
                      <td>No any product</td>
                      @endif
                    

                    </tbody>
                  </table>
                </div>
              </div>
            </div>

 @endsection